version: "3"

services:
  mongo:
    image: mongo:4.4.2-bionic
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${name}
      - MONGO_INITDB_ROOT_PASSWORD=${pwd}
      - MONGO_INITDB_DATABASE=project
    networks:
        extnetwork:
          ipv4_address: 172.24.0.2
  mongo-express:
    image: mongo-express:0.54.0
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${name}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${pwd}
      - ME_CONFIG_BASICAUTH_USERNAME=${name}
      - ME_CONFIG_BASICAUTH_PASSWORD=${pwd}
    links:
      - mongo
    ports:
      - "8081:8081"
    networks:
        extnetwork:
          ipv4_address: 172.24.0.3
  feed-worker:
    image: "node:12"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./jz_feeds_worker:/home/node/app
    ports:
      - "8964:3001"
    command: "yarn start"
networks:
  extnetwork:
    ipam:
      config:
        - subnet: 172.24.0.0/16
