version: "3"

services:
  mongo:
    container_name: mongo
    image: mongo:4.4.2-bionic
    environment:
      - MONGO_INITDB_ROOT_USERNAME=jeff001
      - MONGO_INITDB_ROOT_PASSWORD=mOn90Db001
      - MONGO_INITDB_DATABASE=project
    volumes:
      - mongodbdata:/data/db
    restart: always
    ports:
      - "27017:27017"
    networks:
      extnetwork:
        ipv4_address: 172.24.0.2
  mongo-express:
    container_name: mongo_exp
    image: mongo-express:0.54.0
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_MONGODB_ADMINUSERNAME=jeff001
      - ME_CONFIG_MONGODB_ADMINPASSWORD=mOn90Db001
      - ME_CONFIG_BASICAUTH_USERNAME=jeffexp001
      - ME_CONFIG_BASICAUTH_PASSWORD=mOn90DbExp001
    links:
      - mongo
    ports:
      - "8088:8081"
    networks:
      extnetwork:
        ipv4_address: 172.24.0.3
  feed-worker:
    container_name: worker
    user: "node"
    working_dir: /home/node/app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - ME_CONFIG_MONGODB_ADMINUSERNAME=jeff001
      - ME_CONFIG_MONGODB_ADMINPASSWORD=mOn90Db001
      - MONGO_URL=mongo://mongo/app
    external_links:
      - mongo
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./:/home/node/app
    ports:
      - "8964:3001"
networks:
  extnetwork:
    ipam:
      config:
        - subnet: 172.24.0.0/16

volumes:
  mongodbdata:
